server:
  port: 8000
#  servlet:
#    context-path: /search

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    username: root
    password: ta42X
    url: jdbc:mysql://34.130.90.239:3306/travel_advisory
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true