apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  config.yaml: |
    dbUrl: "jdbc:mysql://34.130.90.239:3306/travel_advisory"
    username: cm9vdA==
    password: dGE0Mlg=
