name: Java CI

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Project_2

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - run: mkdir buildpath
      - run: cp LocationSearchAPI/target/*.jar buildpath
      - run: cp LocationStatusAPI/target/*.jar buildpath
      - uses: actions/upload-artifact@v3
        with:
         name: Package
         path: buildpath
